
GET http://localhost:8080/getUserById/3

###
POST http://localhost:8080/createUser
Content-Type: application/json

{
    "role": "user",
    "email": "johnd6@gmail.com",
    "password": "password",
    "firstName": "John",
    "lastName": "Doe",
    "profilePictureURL": "https://www.google.com" 
}

###

GET http://localhost:8080/getUserByEmail/johnd@gmail.com

